sudo: false

language: cpp

compiler:
    - gcc
    - clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
        packages:
            - cmake
            - g++-4.9
            - libboost-all-dev
            - libbox2d-dev
            - xorg-dev
            - libgl1-mesa-dev
            - libopencv-dev
            - libpython2.7-dev

before_install:
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - "wget https://github.com/glfw/glfw/archive/3.1.zip && unzip 3.1.zip -d . && cd glfw-3.1 &&
      cmake -DCMAKE_INSTALL_PREFIX=$HOME/glfw3 -DCMAKE_BUILD_TYPE=release -DGLFW_BUILD_DOCS=Off
            -DGLFW_BUILD_EXAMPLES=Off -DGLFW_BUILD_TESTS=Off . &&
      cmake --build . && make install && cd -"

before_script:
    - mkdir build && cd build
    - GLFW_LOCATION=$HOME/glfw3 cmake -DCMAKE_BUILD_TYPE=debug ..

script:
    - make
