# ######################################################################### #
# Georgiev Lab (c) 2015-2016                                                #
# ######################################################################### #
# Department of Cybernetics                                                 #
# Faculty of Applied Sciences                                               #
# University of West Bohemia in Pilsen                                      #
# ######################################################################### #
#                                                                           #
# This file is part of CeCe.                                                #
#                                                                           #
# CeCe is free software: you can redistribute it and/or modify              #
# it under the terms of the GNU General Public License as published by      #
# the Free Software Foundation, either version 3 of the License, or         #
# (at your option) any later version.                                       #
#                                                                           #
# CeCe is distributed in the hope that it will be useful,                   #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
# GNU General Public License for more details.                              #
#                                                                           #
# You should have received a copy of the GNU General Public License         #
# along with CeCe.  If not, see <http://www.gnu.org/licenses/>.             #
#                                                                           #
# ######################################################################### #

sudo: required
dist: trusty

cache: ccache

# Disable build for AppVeyor branch
branches:
    except:
        - appveyor

matrix:
    include:
        - os: linux
          compiler: gcc
          env: CECE_RENDER=On DEPLOY=On
        - os: linux
          compiler: gcc
          env: CECE_RENDER=Off DEPLOY=Off
        - os: linux
          compiler: clang
          env: CECE_RENDER=On DEPLOY=Off
        - os: linux
          compiler: clang
          env: CECE_RENDER=Off DEPLOY=Off
        - os: osx
          compiler: clang
          env: CECE_RENDER=On DEPLOY=On
        - os: osx
          compiler: clang
          env: CECE_RENDER=Off DEPLOY=Off
        - os: osx
          compiler: gcc
          env: CECE_RENDER=On DEPLOY=Off
        - os: osx
          compiler: gcc
          env: CECE_RENDER=Off DEPLOY=Off

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-4.9
            - clang-3.6
            - libgl1-mesa-dev
            - xorg-dev
            - libgl1-mesa-dev

before_install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi

install:
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated cmake  || brew upgrade cmake  ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated ccache || brew upgrade ccache ; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated libpng || brew upgrade libpng ; fi

before_script:
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
    - mkdir build
    - pushd build
    - cmake -DCMAKE_BUILD_TYPE=release -DCECE_TESTS_BUILD=On -DCECE_RENDER=$CECE_RENDER ..
    - popd

script:
    - VERBOSE=1 cmake --build build

after_success:
    - pushd build
    - GTEST_COLOR=1 ctest --verbose
    - popd

before_deploy:
    - pushd build
    - cpack -G TGZ
    - popd

deploy:
    provider: bintray
    file: "build/descriptor.json"
    user: "ntsfka"
    key:
        secure: "LPt4Tx0NfVRJpqqfPTnSXsPfHeRFp2OhP3W1P+IR7NrQEUk7o6RTQeEtans6lBsIC2bibwGqX2VN/kvYtC7j48tm4/Fqds6KTm3wUfWWl0t9L12js15n7YaKz6xr8/C/IDIFZYdzjqDbj6wbOTtNNUOvR2fCF4a2z/bgRVZd5YwPk7LmnUeSB/2MPpB/ccJ/ggsFCCUGLN6LiUynTihlBJWaxOJfF96q9B2wHn4GXdhzuZdzfreKqApEHiPeC9Bm+HIuRuGaHgnvmjFGCe0rGO+SHOsL/zjRQioO0+eS4C5V2Z3KmXbTQn0J0F2m072BaJ9i4lUXBEFL7hQUNxi9UnvnRMbskottHhAMYVCA5RhYJOuw4GRdI5PJfsKGDQ0fmy5rRsHKZk0DdrnGLLMJyXViLtjPbuTbMzc3xcAJ0V5fh+sxxF2yHVnjEL2kNe3XCJjCojEA3brEdeoIhz9iuvcbs48Zgzj+SFtgx2Tzvt/gBDmbL5p56+doxnymC2tv+Fw1STyhpU8NtY8Qh0Yo3hNCaXnFIkGL4b+e2ZP0KQeo0l5lgZ5+acGF17+XtNe4yjJV3mDw44qEwWWcgDu9I/U/C/ReajTyStEIws6aRKsnola4v+X6oehh8PPBSOyNJJ2fQiKk5nXwvdHEekSy2KJXwfUitutr8jrtnaClcD8="
    skip_cleanup: true
    on:
        branch: master
        condition: "$DEPLOY = On"

# ######################################################################### #
