
# Container-based
sudo: false

# Operating systems
os:
  - linux
  - osx

# Environment variables
env:
    - VENDOR_DIR=$HOME/vendor/$TRAVIS_OS_NAME

language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
            - boost-latest
#            - llvm-toolchain-precise-3.6
        packages:
            - cmake
            - g++-4.9
#            - clang-3.6
            - libboost-filesystem1.55-dev
            - xorg-dev
            - libgl1-mesa-dev
            - libfreetype6-dev
            - libpython2.7-dev

before_install:
    # Update compiler variables
    - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

    - mkdir -p $VENDOR_DIR
    - ls $VENDOR_DIR

    # Build GLFW3
    - "if [ ! -d $VENDOR_DIR/glfw3 ]; then wget https://github.com/glfw/glfw/archive/3.1.zip -O glfw.zip && unzip glfw.zip -d . && cd glfw-3.1 &&
      cmake -DCMAKE_INSTALL_PREFIX=$VENDOR_DIR/glfw3 -DCMAKE_BUILD_TYPE=release -DGLFW_BUILD_DOCS=Off
            -DGLFW_BUILD_EXAMPLES=Off -DGLFW_BUILD_TESTS=Off . &&
      cmake --build . && make install && cd -; fi"

    # Build Box2D
    - "if [ ! -d $VENDOR_DIR/box2d ]; then wget https://github.com/erincatto/Box2D/archive/v2.3.1.zip -O box2d.zip && unzip box2d.zip && cd Box2D-2.3.1/Box2D &&
      cmake -DCMAKE_INSTALL_PREFIX=$VENDOR_DIR/box2d -DCMAKE_BUILD_TYPE=release -DBOX2D_BUILD_EXAMPLES=Off
            -DBOX2D_BUILD_SHARED=On -DBOX2D_BUILD_STATIC=Off . &&
      cmake --build . && make install && cd -; fi"

    # Build OpenCV
    - "if [ ! -d $VENDOR_DIR/opencv ]; then wget https://github.com/Itseez/opencv/archive/2.4.12.2.zip -O opencv.zip && unzip opencv.zip -d . && cd opencv-2.4.12.2 &&
      cmake -DCMAKE_INSTALL_PREFIX=$VENDOR_DIR/opencv -DCMAKE_BUILD_TYPE=release . &&
      cmake --build . && make install && cd -; fi"

before_script:
    - mkdir build && cd build
    - export GLFW_LOCATION=$VENDOR_DIR/glfw3
    - export BOX2DDIR=$VENDOR_DIR/box2d
    - cmake -DCMAKE_BUILD_TYPE=debug -DOpenCV_DIR=$VENDOR_DIR/opencv/share/OpenCV ..

script:
    - make VERBOSE=1

# Dependencies cache
cache:
    directories:
        - $VENDOR_DIR
