# ######################################################################### #
# Georgiev Lab (c) 2015-2016                                                #
# ######################################################################### #
# Department of Cybernetics                                                 #
# Faculty of Applied Sciences                                               #
# University of West Bohemia in Pilsen                                      #
# ######################################################################### #
#                                                                           #
# This file is part of CeCe.                                                #
#                                                                           #
# CeCe is free software: you can redistribute it and/or modify              #
# it under the terms of the GNU General Public License as published by      #
# the Free Software Foundation, either version 3 of the License, or         #
# (at your option) any later version.                                       #
#                                                                           #
# CeCe is distributed in the hope that it will be useful,                   #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
# GNU General Public License for more details.                              #
#                                                                           #
# You should have received a copy of the GNU General Public License         #
# along with CeCe.  If not, see <http://www.gnu.org/licenses/>.             #
#                                                                           #
# ######################################################################### #

os: Visual Studio 2015

version: 0.5.0.{build}

environment:
    matrix:
        - GENERATOR: Visual Studio 14 2015
          BOOST_ROOT: C:\Libraries\boost_1_59_0
          BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib32-msvc-14.0
        - GENERATOR: MinGW Makefiles
          BOOST_ROOT: C:\Libraries\boost_1_59_0

matrix:
    allow_failures:
        - GENERATOR: MinGW Makefiles

# Branches to build
branches:
    except:
        - travis-ci

init:
    - del c:\programdata\chocolatey\bin\cpack.exe

install:
    - call scripts\ci\install-win32.bat

before_build:
    - call scripts\ci\before_build-win32.bat

build_script:
    - call scripts\ci\build_script-win32.bat

test_script:
    - call scripts\ci\test_script-win32.bat

after_build:
    - call scripts\ci\after_build-win32.bat

artifacts:
    - path: build\CeCe-*-win32.zip
      name: CeCe

# ######################################################################### #
