# ######################################################################### #
# Georgiev Lab (c) 2015-2016                                                #
# ######################################################################### #
# Department of Cybernetics                                                 #
# Faculty of Applied Sciences                                               #
# University of West Bohemia in Pilsen                                      #
# ######################################################################### #
#                                                                           #
# This file is part of CeCe.                                                #
#                                                                           #
# CeCe is free software: you can redistribute it and/or modify              #
# it under the terms of the GNU General Public License as published by      #
# the Free Software Foundation, either version 3 of the License, or         #
# (at your option) any later version.                                       #
#                                                                           #
# CeCe is distributed in the hope that it will be useful,                   #
# but WITHOUT ANY WARRANTY; without even the implied warranty of            #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             #
# GNU General Public License for more details.                              #
#                                                                           #
# You should have received a copy of the GNU General Public License         #
# along with CeCe.  If not, see <http://www.gnu.org/licenses/>.             #
#                                                                           #
# ######################################################################### #

os: Visual Studio 2015

version: 0.6.0.{build}

environment:
    matrix:
        - GENERATOR: Visual Studio 14 2015 Win64
          CECE_RENDER: On
          DEPLOY: On
        - GENERATOR: Visual Studio 14 2015 Win64
          CECE_RENDER: Off
          DEPLOY: Off
        - GENERATOR: Visual Studio 14 2015
          CECE_RENDER: On
          DEPLOY: Off
        - GENERATOR: Visual Studio 14 2015
          CECE_RENDER: Off
          DEPLOY: Off
        - GENERATOR: MinGW Makefiles
          CECE_RENDER: On
          DEPLOY: Off
        - GENERATOR: MinGW Makefiles
          CECE_RENDER: Off
          DEPLOY: Off

matrix:
    allow_failures:
        - GENERATOR: MinGW Makefiles

# Branches to build
branches:
    except:
        - travis-ci

install:
    - git submodule update --init --recursive
    - SET PATH=%PATH:C:\Program Files\Git\usr\bin;=%
    - SET PATH=C:\MinGW\bin;%PATH%
    - call plugins\scripts\ci\install-win32.bat

before_build:
    - call plugins\scripts\ci\before_build-win32.bat

build_script:
    - pushd build && cmake --build . --config Release & popd

# ######################################################################### #
