//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter.h"


// Declare the bitmap loading function
extern void wxC9ED9InitBitmapResources();

static bool bBitmapLoaded = false;


MainFrameBaseClass::MainFrameBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    m_menuBar = new wxMenuBar(0);
    this->SetMenuBar(m_menuBar);
    
    m_menuFile = new wxMenu();
    m_menuBar->Append(m_menuFile, _("&File"));
    
    m_menuItemFileNew = new wxMenuItem(m_menuFile, wxID_NEW, _("&New\tCtrl+N"), wxT(""), wxITEM_NORMAL);
    m_menuFile->Append(m_menuItemFileNew);
    
    m_menuItemFileOpen = new wxMenuItem(m_menuFile, wxID_OPEN, _("&Open...\tCtrl+O"), wxT(""), wxITEM_NORMAL);
    m_menuFile->Append(m_menuItemFileOpen);
    
    m_menuItemFileSave = new wxMenuItem(m_menuFile, wxID_SAVE, _("&Save\tCtrl+S"), wxT(""), wxITEM_NORMAL);
    m_menuFile->Append(m_menuItemFileSave);
    
    m_menuItemFileSaveAs = new wxMenuItem(m_menuFile, wxID_SAVEAS, _("Save &As...\tCtrl+Shift+S"), wxT(""), wxITEM_NORMAL);
    m_menuFile->Append(m_menuItemFileSaveAs);
    
    m_menuFile->AppendSeparator();
    
    m_menuFileRecent = new wxMenu();
    m_menuFile->AppendSubMenu(m_menuFileRecent, _("Recent"));
    
    m_menuFile->AppendSeparator();
    
    m_menuItemFileExit = new wxMenuItem(m_menuFile, wxID_EXIT, _("&Exit\tCtrl+Q"), _("Quit"), wxITEM_NORMAL);
    m_menuFile->Append(m_menuItemFileExit);
    
    m_menuView = new wxMenu();
    m_menuBar->Append(m_menuView, _("&View"));
    
    m_menuItemViewReset = new wxMenuItem(m_menuView, wxID_ANY, _("Reset"), wxT(""), wxITEM_NORMAL);
    m_menuView->Append(m_menuItemViewReset);
    
    m_menuView->AppendSeparator();
    
    m_menuItemViewGrid = new wxMenuItem(m_menuView, wxID_ANY, _("Grid"), wxT(""), wxITEM_CHECK);
    m_menuView->Append(m_menuItemViewGrid);
    
    m_menuItemViewVelocity = new wxMenuItem(m_menuView, wxID_ANY, _("Velocity"), wxT(""), wxITEM_CHECK);
    m_menuView->Append(m_menuItemViewVelocity);
    
    m_menuItemViewInterpolate = new wxMenuItem(m_menuView, wxID_ANY, _("Signal interpolation"), wxT(""), wxITEM_CHECK);
    m_menuView->Append(m_menuItemViewInterpolate);
    
    m_menuSimulation = new wxMenu();
    m_menuBar->Append(m_menuSimulation, _("&Simulation"));
    
    m_menuItemSimulationStart = new wxMenuItem(m_menuSimulation, ID_START, _("&Start\tF5"), wxT(""), wxITEM_NORMAL);
    m_menuSimulation->Append(m_menuItemSimulationStart);
    
    m_menuItemSimulationStop = new wxMenuItem(m_menuSimulation, ID_STOP, _("Sto&p\tF6"), wxT(""), wxITEM_NORMAL);
    m_menuSimulation->Append(m_menuItemSimulationStop);
    
    m_menuItemSimulationStep = new wxMenuItem(m_menuSimulation, ID_STEP, _("S&tep\tF7"), wxT(""), wxITEM_NORMAL);
    m_menuSimulation->Append(m_menuItemSimulationStep);
    
    m_menuItemSimulationRestart = new wxMenuItem(m_menuSimulation, ID_RESTART, _("&Restart\tF8"), wxT(""), wxITEM_NORMAL);
    m_menuSimulation->Append(m_menuItemSimulationRestart);
    
    m_menuSimulation->AppendSeparator();
    
    m_menuItemSimulationScreenshot = new wxMenuItem(m_menuSimulation, wxID_ANY, _("Screenshot"), wxT(""), wxITEM_NORMAL);
    m_menuSimulation->Append(m_menuItemSimulationScreenshot);
    
    m_menuHelp = new wxMenu();
    m_menuBar->Append(m_menuHelp, _("&Help"));
    
    m_menuItemAbout = new wxMenuItem(m_menuHelp, wxID_ABOUT, _("&About..."), wxT(""), wxITEM_NORMAL);
    m_menuHelp->Append(m_menuItemAbout);
    
    m_mainToolbar = this->CreateToolBar(wxTB_TEXT|wxTB_HORIZONTAL|wxTB_FLAT, wxID_ANY);
    m_mainToolbar->SetToolBitmapSize(wxSize(24,24));
    
    m_mainToolbar->AddTool(ID_START, _("Start"), wxXmlResource::Get()->LoadBitmap(wxT("play-24")), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    
    m_mainToolbar->AddTool(ID_STOP, _("Stop"), wxXmlResource::Get()->LoadBitmap(wxT("stop-24")), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    
    m_mainToolbar->AddTool(ID_STEP, _("Step"), wxXmlResource::Get()->LoadBitmap(wxT("step-24")), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    
    m_mainToolbar->AddTool(ID_RESTART, _("Restart"), wxXmlResource::Get()->LoadBitmap(wxT("restart-24")), wxNullBitmap, wxITEM_NORMAL, wxT(""), wxT(""), NULL);
    m_mainToolbar->Realize();
    
    wxBoxSizer* boxSizerMain = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(boxSizerMain);
    
    int *m_glCanvasViewAttr = NULL;
    m_glCanvasView = new CanvasWidget(this, wxID_ANY, m_glCanvasViewAttr, wxDefaultPosition, wxSize(-1,-1), wxFULL_REPAINT_ON_RESIZE);
    wxDELETEA( m_glCanvasViewAttr );
    
    boxSizerMain->Add(m_glCanvasView, 1, wxLEFT|wxRIGHT|wxEXPAND, 5);
    
    m_statusBar = new wxStatusBar(this, wxID_ANY, wxSTB_DEFAULT_STYLE);
    m_statusBar->SetFieldsCount(2);
    this->SetStatusBar(m_statusBar);
    
    SetSizeHints(800,600);
    if ( GetSizer() ) {
         GetSizer()->Fit(this);
    }
    Centre(wxBOTH);
    // Connect events
    this->Connect(m_menuItemFileNew->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnFileNew), NULL, this);
    this->Connect(m_menuItemFileOpen->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnFileOpen), NULL, this);
    this->Connect(m_menuItemFileSave->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnFileSave), NULL, this);
    this->Connect(m_menuItemFileSaveAs->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnFileSaveAs), NULL, this);
    this->Connect(m_menuItemFileExit->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnExit), NULL, this);
    this->Connect(m_menuItemViewReset->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnViewReset), NULL, this);
    this->Connect(m_menuItemViewGrid->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnViewGrid), NULL, this);
    this->Connect(m_menuItemViewGrid->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnViewGridUpdateUi), NULL, this);
    this->Connect(m_menuItemViewVelocity->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnViewVelocity), NULL, this);
    this->Connect(m_menuItemViewVelocity->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnViewVelocityUpdateUi), NULL, this);
    this->Connect(m_menuItemViewInterpolate->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnViewInterpolate), NULL, this);
    this->Connect(m_menuItemViewInterpolate->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnViewInterpolateUpdateUi), NULL, this);
    this->Connect(m_menuItemSimulationStart->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationStart), NULL, this);
    this->Connect(m_menuItemSimulationStart->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnSimulationNotRunningUpdateUi), NULL, this);
    this->Connect(m_menuItemSimulationStop->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnSimulationRunningUpdateUi), NULL, this);
    this->Connect(m_menuItemSimulationStop->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationStop), NULL, this);
    this->Connect(m_menuItemSimulationStep->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationStep), NULL, this);
    this->Connect(m_menuItemSimulationStep->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnSimulationNotRunningUpdateUi), NULL, this);
    this->Connect(m_menuItemSimulationRestart->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationRestart), NULL, this);
    this->Connect(m_menuItemSimulationRestart->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnSimulationNotRunningUpdateUi), NULL, this);
    this->Connect(m_menuItemSimulationScreenshot->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationScreenshot), NULL, this);
    this->Connect(m_menuItemAbout->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnAbout), NULL, this);
    this->Connect(ID_STEP, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationStep), NULL, this);
    this->Connect(ID_RESTART, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationRestart), NULL, this);
    
}

MainFrameBaseClass::~MainFrameBaseClass()
{
    this->Disconnect(m_menuItemFileNew->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnFileNew), NULL, this);
    this->Disconnect(m_menuItemFileOpen->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnFileOpen), NULL, this);
    this->Disconnect(m_menuItemFileSave->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnFileSave), NULL, this);
    this->Disconnect(m_menuItemFileSaveAs->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnFileSaveAs), NULL, this);
    this->Disconnect(m_menuItemFileExit->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnExit), NULL, this);
    this->Disconnect(m_menuItemViewReset->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnViewReset), NULL, this);
    this->Disconnect(m_menuItemViewGrid->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnViewGrid), NULL, this);
    this->Disconnect(m_menuItemViewGrid->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnViewGridUpdateUi), NULL, this);
    this->Disconnect(m_menuItemViewVelocity->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnViewVelocity), NULL, this);
    this->Disconnect(m_menuItemViewVelocity->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnViewVelocityUpdateUi), NULL, this);
    this->Disconnect(m_menuItemViewInterpolate->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnViewInterpolate), NULL, this);
    this->Disconnect(m_menuItemViewInterpolate->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnViewInterpolateUpdateUi), NULL, this);
    this->Disconnect(m_menuItemSimulationStart->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationStart), NULL, this);
    this->Disconnect(m_menuItemSimulationStart->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnSimulationNotRunningUpdateUi), NULL, this);
    this->Disconnect(m_menuItemSimulationStop->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnSimulationRunningUpdateUi), NULL, this);
    this->Disconnect(m_menuItemSimulationStop->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationStop), NULL, this);
    this->Disconnect(m_menuItemSimulationStep->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationStep), NULL, this);
    this->Disconnect(m_menuItemSimulationStep->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnSimulationNotRunningUpdateUi), NULL, this);
    this->Disconnect(m_menuItemSimulationRestart->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationRestart), NULL, this);
    this->Disconnect(m_menuItemSimulationRestart->GetId(), wxEVT_UPDATE_UI, wxUpdateUIEventHandler(MainFrameBaseClass::OnSimulationNotRunningUpdateUi), NULL, this);
    this->Disconnect(m_menuItemSimulationScreenshot->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationScreenshot), NULL, this);
    this->Disconnect(m_menuItemAbout->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnAbout), NULL, this);
    this->Disconnect(ID_STEP, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationStep), NULL, this);
    this->Disconnect(ID_RESTART, wxEVT_COMMAND_TOOL_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnSimulationRestart), NULL, this);
    
}
