//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef WXCRAFTER_BASE_CLASSES_H
#define WXCRAFTER_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/menu.h>
#include <wx/toolbar.h>
#include <wx/sizer.h>
#include <wx/splitter.h>
#include <wx/panel.h>
#include <wx/glcanvas.h>
#include "CanvasWidget.h"
#include <wx/stc/stc.h>
#include <wx/statusbr.h>

class MainFrameBaseClass : public wxFrame
{
public:
    enum {
        ID_RESTART = 1001,
        ID_START = 1002,
        ID_STEP = 1003,
        ID_STOP = 1004,
    };
protected:
    wxMenuBar* m_menuBar;
    wxMenu* m_menuFile;
    wxMenuItem* m_menuItemFileNew;
    wxMenuItem* m_menuItemFileOpen;
    wxMenuItem* m_menuItemFileSave;
    wxMenuItem* m_menuItemFileSaveAs;
    wxMenuItem* m_menuItemFileSep1;
    wxMenu* m_menuFileRecent;
    wxMenuItem* m_menuItemFileSep2;
    wxMenuItem* m_menuItemFileExit;
    wxMenu* m_menuView;
    wxMenuItem* m_menuItemTop;
    wxMenuItem* m_menuItemIsometric;
    wxMenu* m_menuSimulation;
    wxMenuItem* m_menuItemSimulationStart;
    wxMenuItem* m_menuItemSimulationStop;
    wxMenuItem* m_menuItemSimulationStep;
    wxMenuItem* m_menuItemSimulationRestart;
    wxMenu* m_menuHelp;
    wxMenuItem* m_menuItemAbout;
    wxToolBar* m_mainToolbar;
    wxSplitterWindow* m_splitterMain;
    wxPanel* m_splitterPageView;
    CanvasWidget* m_glCanvasView;
    wxPanel* m_splitterPageSource;
    wxStyledTextCtrl* m_stcSource;
    wxStatusBar* m_statusBar;

protected:
    virtual void OnFileNew(wxCommandEvent& event) { event.Skip(); }
    virtual void OnFileOpen(wxCommandEvent& event) { event.Skip(); }
    virtual void OnFileSave(wxCommandEvent& event) { event.Skip(); }
    virtual void OnFileSaveAs(wxCommandEvent& event) { event.Skip(); }
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnViewTop(wxCommandEvent& event) { event.Skip(); }
    virtual void OnViewIsometric(wxCommandEvent& event) { event.Skip(); }
    virtual void OnSimulationStart(wxCommandEvent& event) { event.Skip(); }
    virtual void OnSimulationNotRunningUpdateUi(wxUpdateUIEvent& event) { event.Skip(); }
    virtual void OnSimulationRunningUpdateUi(wxUpdateUIEvent& event) { event.Skip(); }
    virtual void OnSimulationStop(wxCommandEvent& event) { event.Skip(); }
    virtual void OnSimulationStep(wxCommandEvent& event) { event.Skip(); }
    virtual void OnSimulationRestart(wxCommandEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }

public:
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Cell simulator"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800,600), long style = wxCAPTION|wxRESIZE_BORDER|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxSYSTEM_MENU|wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};

#endif
