# Generated by CMakePlugin
.PHONY: all clean $(MAKECMDGOALS)

# Parent project
PARENT          := ../gui
PARENT_MAKEFILE := gui.mk

all:
	$(MAKE) -C "$(PARENT)" -f "$(PARENT_MAKEFILE)" parser

clean:
	$(MAKE) -C "$(PARENT)" -f "$(PARENT_MAKEFILE)" parser clean

